/* THE CONTENT SECURITY POLICY, AND THE FRAME HEADERS, ON EVERY RESPONSE.
 *
 * scripts/csp.py builds one policy per kind of page from the pages
 * themselves (every inline script hashed, at build time, last) and writes
 * public/meta-csp.json. This reads that file once per isolate through
 * env.ASSETS and sets the header. Nobody types a hash, so an edit to
 * index.html cannot leave the live site blank: the page and its hashes change
 * in the same build and the same deploy.
 *
 * WHY A HEADER AND NOT A <meta> TAG. A meta policy cannot run report-only,
 * cannot carry frame-ancestors, and Cloudflare reads the nonce for its Bot
 * Fight Mode snippet from the HEADER only. _headers is no use either: it is
 * not applied to responses a Function produced, and every request here
 * passes through the root middleware.
 *
 * THE NONCE is minted per response and never written into our own HTML. It
 * exists for the one inline script we do not write: the snippet Cloudflare
 * injects at the edge (seen live on sledjobs.com, 2026-10-09), which copies
 * the nonce from this header.
 *
 * REPORT FIRST. CSP_MODE "report" sends Content-Security-Policy-Report-Only:
 * the browser runs everything and prints what it WOULD have blocked in the
 * console. "enforce" blocks. The gate's holding page is enforced in both,
 * because it carries no script of ours. There is no report endpoint: on the
 * Free plan every report would be a Function request.
 *
 * IT NEVER COSTS A PAGE. A missing or garbled manifest, an ASSETS fetch that
 * throws, a path no route matches: the response goes out exactly as it came,
 * with only the frame headers it already had. A policy that fails closed
 * here is a blank site. */

export const CSP_MODE = "report";

/* FRAME PROTECTION ON THE TOKEN PAGES AND THE ADMIN, set here and not only
 * in _headers. /alerts holds a subscriber's token and a one-click delete;
 * /claim confirms a company claim from a mailed link; /admin holds bulk
 * rulings. Framed, any of them is a clickjacking target (build_site.
 * write_headers has the full case). Cloudflare's own docs say _headers rules
 * are "not applied to responses generated by Pages Functions", so they are
 * set on the response itself, on every spelling (launch audit, 2026-10-06).
 * The public board stays embeddable. */
export const NO_FRAME = new Set(["/alerts", "/alerts.html", "/claim", "/claim.html"]);
const FRAME = "frame-ancestors 'none'";
export const framed = (path) => NO_FRAME.has(path) || /^\/admin(\/|$)/.test(path);

let MANIFEST = null;            // per isolate; a failure is retried next time

async function manifest(env, request) {
  if (MANIFEST) return MANIFEST;
  if (!env || !env.ASSETS) return null;
  try {
    const u = new URL(request.url);
    u.pathname = "/meta-csp.json";
    u.search = "";
    const res = await env.ASSETS.fetch(u.toString());
    if (!res.ok) return null;
    const m = await res.json();
    if (!m || !Array.isArray(m.routes) || !m.policies || typeof m.policies !== "object") return null;
    const routes = m.routes.map(([k, rx]) => [String(k), new RegExp(rx)]);
    for (const [k] of routes) {
      const p = m.policies[k];
      if (typeof p !== "string" || !p.includes("{{NONCE}}")) return null;
    }
    MANIFEST = { routes, policies: m.policies };
    return MANIFEST;
  } catch {
    return null;
  }
}

export function nonce() {
  const b = new Uint8Array(18);
  crypto.getRandomValues(b);
  return btoa(String.fromCharCode(...b));
}

function decodedPath(request) {
  let path = new URL(request.url).pathname;
  try { path = decodeURIComponent(path); } catch { /* malformed: as sent */ }
  return path;
}

/* The policy for this response, or null. `holding` is the gate's refusal. */
export async function policyFor(request, env, { holding = false } = {}) {
  const m = await manifest(env, request);
  if (!m) return null;
  const path = decodedPath(request);
  const kind = holding ? "holding" : (m.routes.find(([, rx]) => rx.test(path)) || [])[0];
  const tpl = kind && Object.hasOwn(m.policies, kind) ? m.policies[kind] : null;
  if (typeof tpl !== "string") return null;
  const origin = new URL(request.url).origin;
  if (!/^https?:\/\/[a-z0-9.-]+(:\d+)?$/i.test(origin)) return null;
  return tpl.replaceAll("{{NONCE}}", nonce()).replaceAll("{{ORIGIN}}", origin);
}

/* Frame headers where they belong, and the policy on every HTML response. */
export async function secure(res, request, env, { holding = false, mode = CSP_MODE } = {}) {
  const path = decodedPath(request);
  const isFramed = framed(path);
  const html = (res.headers.get("content-type") || "").includes("text/html");
  if (!isFramed && !html) return res;
  const out = new Response(res.body, res);
  if (isFramed) {
    out.headers.set("X-Frame-Options", "DENY");
    out.headers.set("Content-Security-Policy", FRAME);
  }
  if (!html) return out;
  let p = null;
  try { p = await policyFor(request, env, { holding }); } catch { p = null; }
  if (!p) return out;
  if (holding || mode === "enforce") {
    out.headers.set("Content-Security-Policy", isFramed ? `${p}; ${FRAME}` : p);
  } else {
    out.headers.set("Content-Security-Policy-Report-Only", p);
  }
  return out;
}

/* For a test: forget the manifest this isolate read. */
export function _reset() { MANIFEST = null; }
