import json
OUT="/private/tmp/claude-501/-Users-wyethwest/bae54666-b02f-4b55-98ed-4e5a5f866107/scratchpad/dock-work/data/conference_intake/researched/batch-2.json"
d=json.load(open(OUT))
d["researched"]+=[
{"verdict":"govtech","company_name":"Cogsdale Corporation","website":"https://www.cogsdale.com","description":"Utility billing, customer information, and financial management ERP for municipal utilities and local governments","hq_location":"Ottawa, ON, Canada","year_founded":1997,"sector":"General Gov","category":"Finance & ERP","source_event":"AWWA ACE 2026","notes":"A division of N. Harris Computer Corporation (Constellation Software) since 2013. Company site now lists 1 Antares Drive, Ottawa, ON, the Harris campus address; older directory listings still show the original Charlottetown, PE base. Founding year 1997 from company profile databases, not the company site."},
{"verdict":"supplier","company_name":"INFRIQ","website":"https://infriq.com","description":"Advisory and integration services helping water and wastewater utilities connect AMI, SCADA, and GIS systems","sector":"Public Works","category":"Suppliers & Services","source_event":"AWWA ACE 2026","notes":"Reads as a consulting and enablement firm rather than a product company: the site describes strategies, programs, and coordination with no named software product, pricing, or demo. Positions itself as a Wetwork Group company, and Wetwork Group is a water utility advisory practice. HQ and founding year not found by these searches."},
{"verdict":"govtech","company_name":"Nobel Systems, Inc.","website":"https://www.nobel-systems.com","description":"GeoViewer GIS asset management, field operations, and pressure monitoring software for water districts and municipal utilities","hq_location":"Redlands, CA","year_founded":1992,"sector":"Public Works","category":"Water","source_event":"AWWA ACE 2026","notes":"Founding year from Crunchbase/company directory listings; the company site states '32 years of experience,' consistent with 1992."},
{"verdict":"govtech","company_name":"SmartWorks","website":"https://harrissmartworks.com","description":"Meter data management, utility analytics, and customer engagement software for electric, water, and gas utilities","hq_location":"Nepean, ON, Canada","sector":"Utilities & Energy","category":"Grid & Energy","source_event":"AWWA ACE 2026","notes":"A division of N. Harris Computer Corporation, sister unit to Cogsdale at the same Ottawa-area campus. Founding year not found by these searches."},
{"verdict":"govtech","company_name":"VTScada by Trihedral","website":"https://www.vtscada.com","description":"SCADA software for monitoring and controlling water and wastewater treatment, pumping, and other utility infrastructure","hq_location":"Bedford, NS, Canada","year_founded":1986,"sector":"Public Works","category":"Water","source_event":"AWWA ACE 2026","notes":"Legal entity is Trihedral Engineering Limited, acquired by Delta Electronics in 2020. Judgment call on verdict: water and wastewater is its lead market and the reason it exhibits at AWWA, but VTScada is also sold into oil and gas, power generation, manufacturing, and marine, so an argument exists for scope review."},
{"verdict":"scope_review","company_name":"Vexcel","website":"https://vexceldata.com","description":"Aerial imagery, 3D models, and AI-derived property data licensed to government, insurance, utilities, telecom, energy, and financial services","hq_location":"Boulder, CO","year_founded":1992,"sector":"General Gov","category":"IT & AI Platforms","source_event":"IAAO 2026","notes":"Given URL vexcelgroup.com did not respond; the live commercial site is vexceldata.com (footer entity Vexcel Imaging US, Inc.). Horizontal geospatial data business: government property assessment is one of eight named industries alongside insurance, which is the largest commercial segment. Founded 1992 in Graz, Austria as Vexcel Imaging; US group HQ now Boulder, CO."},
{"verdict":"govtech","company_name":"PAIRIN","website":"https://www.pairin.com","description":"My Journey career planning, skills assessment, and case management platform for state workforce agencies, workforce boards, and schools","hq_location":"Denver, CO","year_founded":2012,"sector":"Health & Human Services","category":"Workforce & Labor","source_event":"NASWA 2025","notes":"Acquired by DigiCap LLC in May 2025, and some recent press carries a Bethesda, MD dateline; the company's own contact page still lists 3330 Larimer Street, Denver, CO. Founding year from Crunchbase/CB Insights; one source says 2011."},
{"verdict":"govtech","company_name":"SaraWorks","website":"https://saraworks.com","description":"HIPAA-compliant client communication, scheduling, and case-note automation software for vocational rehabilitation and workforce development agencies","hq_location":"Liberty Lake, WA","year_founded":2015,"sector":"Health & Human Services","category":"Workforce & Labor","source_event":"NASWA 2025","notes":"Part of Radicle Health since November 2022. Originated in 2015 out of the Council of State Administrators of Vocational Rehabilitation's WINTAC project; HQ and founding year from directory listings and the company's own acquisition announcement rather than an about page."},
{"verdict":"scope_review","company_name":"KYND","website":"https://www.kynd.io","description":"Cyber risk scanning and portfolio monitoring software sold to insurance brokers, underwriters, financial services firms, and risk pools","hq_location":"London, United Kingdom","year_founded":2018,"sector":"General Gov","category":"IT & AI Platforms","source_event":"PRIMA 2026","notes":"General-purpose cyber risk analytics distributed mainly through the insurance channel; public entity risk pools are one buyer segment among brokers, carriers, and corporates. Backed by Verisk and BGF. HQ and founding year from funding press, not the company site."},
{"verdict":"scope_review","company_name":"Siteimprove","website":"https://www.siteimprove.com","description":"Web accessibility, content quality, analytics, and SEO software for organizations in government, higher education, healthcare, finance, and retail","hq_location":"Copenhagen, Denmark","year_founded":2003,"sector":"General Gov","category":"Citizen Services","source_event":"3CMA 2026","notes":"Horizontal digital-presence platform; government and higher ed are two of many named verticals, with corporates such as Vodafone, BT, and Costco as flagship customers. Legal entity Siteimprove A/S."}
]
json.dump(d,open(OUT,"w"),indent=1)
print(len(d["researched"]),"total")
