import json
OUT="/private/tmp/claude-501/-Users-wyethwest/bae54666-b02f-4b55-98ed-4e5a5f866107/scratchpad/dock-work/data/conference_intake/researched/batch-2.json"
d=json.load(open(OUT))
d["researched"]+=[
{"verdict":"govtech","company_name":"Velosimo","website":"https://www.velosimo.com","description":"No-code integration platform with prebuilt connectors linking government systems such as Accela, Tyler, and Laserfiche","hq_location":"Herriman, UT","year_founded":2018,"sector":"General Gov","category":"IT & AI Platforms","source_event":"GFOA 2026","notes":"HQ and founding year not on the company site; taken from its $11M Series A press coverage and Crunchbase/CB Insights profiles."},
{"verdict":"scope_review","company_name":"Oracle","website":"https://www.oracle.com","description":"Cloud infrastructure, database, ERP, and HCM software sold to enterprises and governments across every industry","hq_location":"Austin, TX","year_founded":1977,"sector":"General Gov","category":"IT & AI Platforms","source_event":"PSHRA 2026","notes":"Candidate was listed as the US operating entity Oracle America, Inc.; the canonical brand is Oracle (Oracle Corporation). Horizontal big-tech vendor with a public sector division, not a govtech-specific company."},
{"verdict":"govtech","company_name":"i3 Verticals Education (PaySchools)","website":"https://i3verticals.com/education","description":"K-12 payments, meal account, forms, and ticketing software for school districts","hq_location":"Nashville, TN","year_founded":2012,"sector":"K-12 Schools","category":"Operations & SIS","source_event":"SNA ANC 2027","notes":"Given URL i3education.org 301-redirects to i3verticals.com/education; PaySchools and SchoolPay are product brands of i3 Verticals' education segment. 2012 is the founding of parent i3 Verticals, Inc. (Nashville), not of the PaySchools brand."},
{"verdict":"govtech","company_name":"Saavor","website":"https://www.saavor.com","description":"AI point-of-sale and dining operations software for K-12 school nutrition programs and campus dining","hq_location":"Fords, NJ","year_founded":2019,"sector":"K-12 Schools","category":"Operations & SIS","source_event":"SNA ANC 2027","notes":"No URL was supplied; saavor.com confirmed as the company site. The site itself is nearly all images, so HQ and founding year come from CB Insights/Crunchbase-style profiles rather than the company's own pages. Techstars NYC alumnus."},
{"verdict":"govtech","company_name":"Builterra","website":"https://builterra.com","description":"Construction contract administration software covering quantity take-off, bidding, field inspection, and payment certification for municipalities and civil engineering consultants","hq_location":"Richmond Hill, ON, Canada","year_founded":2014,"sector":"Public Works","category":"Streets","source_event":"NACE 2026","notes":"No URL was supplied. Product of AEC Solutions Inc., which rebranded to Builterra. The company site's footer address is Richmond Hill, ON while some directory listings say Oshawa, ON; used the company's own address. Founding year 2014 from its own press releases."},
{"verdict":"scope_review","company_name":"Checkbox","website":"https://www.checkbox.ai","description":"No-code legal request intake, matter management, and workflow automation software for in-house legal teams","hq_location":"Sydney, Australia","year_founded":2016,"sector":"Courts & Justice","category":"Prosecution & Defense","source_event":"IMLA 2026","notes":"No URL was supplied; resolved to checkbox.ai (Checkbox Technology Pty Ltd), not the unrelated Checkbox survey software at checkbox.com. Horizontal legal-ops product whose named customers are corporates (BMW, PepsiCo, SAP, Deloitte); municipal law departments are one buyer type among many."},
{"verdict":"govtech","company_name":"BetterAge","website":"https://www.betterage.net","description":"AI health and well-being assessment platform used by Area Agencies on Aging to screen older adults and route them to local services","hq_location":"San Francisco, CA","sector":"Health & Human Services","category":"Aging & Veterans","source_event":"USAging 2026","notes":"Given URL betterage.com refuses connections; the live site is betterage.net. Confirmed as the USAging exhibitor via the USAging/BetterAge national partnership announcement. NIH/NIA SBIR-funded ($5.5M in grants). Founding year not found by these searches."},
{"verdict":"govtech","company_name":"RemoteCOM","website":"https://remotecom.net","description":"Computer, smartphone, and tablet monitoring software for pretrial, probation, and parole supervision agencies","hq_location":"Round Rock, TX","sector":"Courts & Justice","category":"Probation & Supervision","source_event":"APPA Probation 2026","notes":"The public site is a thin login page with almost no company content; description and HQ assembled from its BBB listing, Crunchbase, and news coverage. Flagged the company disclosed a 2025 data breach of its monitoring product. Founding year not found by these searches."},
{"verdict":"scope_review","company_name":"Multi-Health Systems Inc. (MHS)","website":"https://mhs.com","description":"Psychological and risk-needs assessments delivered through an online assessment platform, sold to clinical, education, public safety, and corporate talent buyers","hq_location":"Toronto, ON, Canada","year_founded":1983,"sector":"Health & Human Services","category":"Behavioral Health","source_event":"APPA Probation 2026","notes":"Judgment call: MHS is an assessment publisher rather than a pure software company, and it sells across clinical, education, corrections, and corporate HR. Its offender risk-needs instruments (LS/CMI, YLS/CMI) are the reason it exhibits at APPA, but the business is not government-specific."},
{"verdict":"govtech","company_name":"Aventiv Technologies","website":"https://www.aventiv.com","description":"Inmate communications, tablets, electronic monitoring, and trust fund payment systems for corrections and community supervision agencies","hq_location":"Dallas, TX","sector":"Public Safety","category":"Corrections","source_event":"APPA Probation 2026","notes":"Parent of Securus Technologies, Securus Monitoring, and JPay. Securus dates to 1986 but Aventiv is a later holding-company rebrand, so no founding year is recorded here rather than attributing the wrong one."}
]
json.dump(d,open(OUT,"w"),indent=1)
print(len(d["researched"]),"total")
