import json
OUT="/private/tmp/claude-501/-Users-wyethwest/bae54666-b02f-4b55-98ed-4e5a5f866107/scratchpad/dock-work/data/conference_intake/researched/batch-2.json"
d=json.load(open(OUT))
d["researched"]+=[
{"verdict":"scope_review","company_name":"Kipu Health","website":"https://www.kipuhealth.com","description":"CRM, EMR, billing, and compliance platform for addiction treatment, eating disorder, and behavioral health facilities","hq_location":"Miami, FL","sector":"Health & Human Services","category":"Behavioral Health","source_event":"NatCon 2026","notes":"Judgment call worth a second look: a real behavioral health software product, but its named market is private residential and outpatient treatment centers rather than county or state agencies, so it may not belong on a public-sector tracker. Founding year not found by these searches."},
{"verdict":"govtech","company_name":"MIYO Health","website":"https://miyohealth.com","description":"IEP compliance platform, universal mental health screening, and teletherapy staffing for school districts, provider networks, and state agencies","year_founded":2019,"sector":"K-12 Schools","category":"Operations & SIS","source_event":"NatCon 2026","notes":"Hybrid model: the IEP and screening platform is real software, but a large share of the business is contracted clinician staffing and direct services, which is closer to a service provider than a product company. HQ not published on the site and not found by these searches."},
{"verdict":"scope_review","company_name":"Oracle Health","website":"https://www.oracle.com/health/","description":"Electronic health record and clinical data platform for hospitals, health systems, and behavioral health providers","hq_location":"Kansas City, MO","sector":"Health & Human Services","category":"Behavioral Health","source_event":"NatCon 2026","notes":"This is Oracle's healthcare division, the former Cerner, acquired by Oracle in 2022 and still operating from the Kansas City area campus. It is the same corporate entity as the separate Oracle candidate from PSHRA 2026, so the two should probably be merged rather than carded twice. Founding year omitted because Oracle (1977), Cerner (1979), and Oracle Health (2022) are three different dates."},
{"verdict":"govtech","company_name":"QUALO","website":"https://www.qualo.net","description":"Case management EMR, outcome analytics, and revenue cycle platform for behavioral health and human services organizations","sector":"Health & Human Services","category":"Behavioral Health","source_event":"NatCon 2026","notes":"Low-confidence record: qualo.net renders entirely client-side, so both WebFetch and curl returned only navigation labels. The description is assembled from those labels (Case Management EMR, Behavioral Health, Human Services, Outcome Analytics Platform, Revenue Cycle Services) rather than from prose on the page. HQ, founding year, and the public-sector share of its customer base are all unconfirmed and should be checked by hand."},
{"verdict":"govtech","company_name":"Beacon by Trek Medics","website":"https://www.trekmedics.org/beacon","description":"Mobile-phone-based emergency dispatch and responder coordination software for EMS, fire, disaster response, and alternative crisis response teams","year_founded":2010,"sector":"Public Safety","category":"EMS","source_event":"NatCon 2026","notes":"Trek Medics International is a 501(c)(3) nonprofit, founded 2010, and Beacon is its software product, prototyped in 2012 and now used in 20+ countries; the nonprofit structure may matter for how this is carded. FirstNet certified. HQ city not published on the site and not found by these searches."},
{"verdict":"govtech","company_name":"ASLdeafined","website":"https://www.asldeafined.com","description":"Subscription American Sign Language video lesson library and dictionary for public libraries, schools, colleges, and public safety agencies","hq_location":"Auburn Hills, MI","sector":"General Gov","category":"Libraries","source_event":"PLA 2026","notes":"Institutional subscriptions are priced separately from individual ones, so libraries and schools are genuine buyers rather than incidental users. Founding year not found by these searches."},
{"verdict":"scope_review","company_name":"Candid","website":"https://candid.org","description":"Database of roughly 1.9 million US nonprofits plus grants and funder data, licensed to nonprofits, grantmakers, and public libraries","hq_location":"New York, NY","year_founded":2019,"sector":"General Gov","category":"Libraries","source_event":"PLA 2026","notes":"Candid is itself a 501(c)(3) nonprofit (EIN 13-1837418) formed in 2019 by the merger of GuideStar and Foundation Center, so 2019 is the merged entity's date, not the lineage's. Its primary users are nonprofits and funders; public libraries are one distribution channel, which is why this is flagged rather than carded as govtech. HQ from general reference sources; the site's contact page did not resolve."},
{"verdict":"scope_review","company_name":"Data Axle","website":"https://www.data-axle.com","description":"US business and consumer reference databases, sold to marketers broadly and to libraries and academic institutions as Reference Solutions","hq_location":"Grapevine, TX","year_founded":1972,"sector":"General Gov","category":"Libraries","source_event":"PLA 2026","notes":"Reference Solutions is the library-facing product line of a general-purpose B2B and consumer data company (formerly Infogroup), which is why this is scope review rather than govtech. Corporate locations listed are Grapevine TX, Boston MA, and Omaha NE, with Grapevine listed first; the site says 'since 1972' rather than naming a founding year outright."},
{"verdict":"govtech","company_name":"Gimlet","website":"https://gimlet.us","description":"Hosted reference desk statistics tracking and reporting software for public and academic libraries","year_founded":2008,"sector":"General Gov","category":"Libraries","source_event":"PLA 2026","notes":"Operated by Sidecar Publications LLC, a two-person partnership; the site says 'made in Minnesota and Wisconsin' without naming a city, so no HQ is recorded. Founding year inferred from the site's own '2008-2026' copyright range rather than a stated date."},
{"verdict":"govtech","company_name":"Library Market","website":"https://www.librarymarket.com","description":"Library website design, event and room booking calendars, and branding services for public libraries","hq_location":"Jonesboro, AR","sector":"General Gov","category":"Libraries","source_event":"PLA 2026","notes":"Products are LibraryWebsite, LibraryCalendar, and LibraryBrand. The site states Library Market, LibraryIQ, and OrangeBoy now operate as one organization, so the corporate entity may have changed. Roughly half the offering (websites, branding) is agency-style service work rather than product. Founding year not found by these searches."}
]
json.dump(d,open(OUT,"w"),indent=1)
print(len(d["researched"]),"total")
