import json
OUT="/private/tmp/claude-501/-Users-wyethwest/bae54666-b02f-4b55-98ed-4e5a5f866107/scratchpad/dock-work/data/conference_intake/researched/batch-2.json"
d=json.load(open(OUT))
d["researched"]+=[
{"verdict":"govtech","company_name":"Meescan Inc.","website":"https://www.meescan.com","description":"Self-checkout software, kiosks, and RFID equipment for public, academic, and school libraries","hq_location":"Abbotsford, BC, Canada","sector":"General Gov","category":"Libraries","source_event":"PLA 2026","notes":"Sells hardware kiosks and RFID gear alongside the app, so part of the revenue is equipment rather than software. Founding year not found by these searches."},
{"verdict":"govtech","company_name":"OverDrive","website":"https://company.overdrive.com","description":"Digital ebook, audiobook, and video lending platform for public libraries, K-12 schools, and academic institutions","hq_location":"Cleveland, OH","year_founded":1986,"sector":"General Gov","category":"Libraries","source_event":"PLA 2026","notes":"Consumer-facing apps are Libby, Sora, Kanopy, and TeachingBooks. Founding year 1986 is stated on the company's own history page; HQ is from general reference sources because the site does not publish an address."},
{"verdict":"scope_review","company_name":"SenSource, Inc.","website":"https://www.sensourceinc.com","description":"Stereo-video people counting sensors and occupancy analytics software for retail, libraries, museums, campuses, and public buildings","hq_location":"Youngstown, OH","year_founded":2002,"sector":"General Gov","category":"Libraries","source_event":"PLA 2026","notes":"Horizontal traffic-analytics vendor: retail is listed first among ten industries, and the offering is a sensor-plus-software package with installation services, so it is part hardware business."},
{"verdict":"govtech","company_name":"The Library Corporation","website":"https://www.tlcdelivers.com","description":"Integrated library system, cataloging, and patron discovery software for public, school, and academic libraries","hq_location":"Inwood, WV","year_founded":1974,"sector":"General Gov","category":"Libraries","source_event":"PLA 2026","notes":"Known as TLC. Products include Library-Solution, CARL-Solution, ITS-MARC, and eBiblioFile; the site states continuous operation under the same ownership since 1974."},
{"verdict":"scope_review","company_name":"Action1","website":"https://www.action1.com","description":"Cloud patch management and endpoint vulnerability remediation software for IT teams across industries","sector":"General Gov","category":"IT & AI Platforms","source_event":"EDUCAUSE 2026","notes":"Could not read the site: action1.com serves a Cloudflare JavaScript challenge to WebFetch and to curl with full browser headers, and the session's web search budget was exhausted before an alternate source could be checked. Verdict, description, and category rest on general knowledge of Action1 as a horizontal patch management vendor and should be verified by hand; HQ and founding year are deliberately omitted rather than guessed."},
{"verdict":"govtech","company_name":"Apporto","website":"https://www.apporto.com","description":"Cloud virtual desktop and virtual computer lab software for universities, colleges, and schools","sector":"Higher Education","category":"IT & Administration","source_event":"EDUCAUSE 2026","notes":"Education is the lead market at 350+ institutions, but Apporto also sells desktop-as-a-service to businesses, so it is not exclusively an education vendor. HQ and founding year are not published on the site and were not found by these searches."},
{"verdict":"govtech","company_name":"Blackboard","website":"https://www.blackboard.com","description":"Learning management system plus accessibility and analytics tools for higher education, K-12, government, and corporate training","hq_location":"Boca Raton, FL","year_founded":1997,"sector":"Higher Education","category":"IT & Administration","source_event":"EDUCAUSE 2026","notes":"Corporate history is tangled: Blackboard merged with Anthology in 2021, and Anthology took the Blackboard name in 2025; the site footer reads Blackboard T&L, LLC. HQ is the Anthology/Blackboard Boca Raton base from general reference sources, not the site. Founding year 1997 is from the site's own 'Since 1997' line."},
{"verdict":"scope_review","company_name":"Carousel Digital Signage","website":"https://www.carouselsignage.com","description":"Cloud digital signage content management and emergency messaging software for schools, campuses, offices, hospitals, and government buildings","hq_location":"Minneapolis, MN","sector":"General Gov","category":"IT & AI Platforms","source_event":"EDUCAUSE 2026","notes":"A product of Tightrope Media Systems. Horizontal signage platform sold across five named industries. The site claims nearly 30 years in business but never states a founding year, so none is recorded."},
{"verdict":"scope_review","company_name":"Commvault","website":"https://www.commvault.com","description":"Data backup, cyber recovery, and identity resilience software for enterprises across all industries","hq_location":"Tinton Falls, NJ","year_founded":1996,"sector":"General Gov","category":"IT & AI Platforms","source_event":"EDUCAUSE 2026","notes":"Horizontal enterprise data protection vendor; government, healthcare, financial services, and education are named as verticals. Publicly traded (NASDAQ: CVLT). HQ and founding year from general reference sources, not the site."},
{"verdict":"scope_review","company_name":"Cvent","website":"https://www.cvent.com","description":"Event registration, venue sourcing, mobile app, and check-in software for event and marketing teams across all industries","hq_location":"Tysons Corner, VA","year_founded":1999,"sector":"Parks & Rec","category":"Events & Tourism","source_event":"EDUCAUSE 2026","notes":"Horizontal event management platform with a higher-ed page; the company markets on 89% of the Fortune 100 as customers. Legal name Cvent, Inc. Address from the site footer; founding year from general reference sources, matching the site's '25+ years' claim. Sector assignment is awkward: the product is event software, so it was mapped to Events & Tourism rather than to the conference it exhibited at."}
]
json.dump(d,open(OUT,"w"),indent=1)
print(len(d["researched"]),"total")
