import json
OUT="/private/tmp/claude-501/-Users-wyethwest/bae54666-b02f-4b55-98ed-4e5a5f866107/scratchpad/dock-work/data/conference_intake/researched/batch-2.json"
d=json.load(open(OUT))
d["researched"]+=[
{"verdict":"scope_review","company_name":"Microsoft","website":"https://www.microsoft.com","description":"Cloud infrastructure, productivity, and AI software sold to enterprises, governments, and consumers worldwide","hq_location":"Redmond, WA","year_founded":1975,"sector":"General Gov","category":"IT & AI Platforms","source_event":"NASCIO 2026","notes":"Big-tech horizontal vendor with a public sector division; not govtech-specific."},
{"verdict":"scope_review","company_name":"Ping Identity","website":"https://www.pingidentity.com","description":"Identity and access management, verification, and fraud protection software for large enterprises","hq_location":"Denver, CO","year_founded":2002,"sector":"General Gov","category":"IT & AI Platforms","source_event":"NASCIO 2026","notes":"General-purpose IAM: the company markets itself on Fortune 100 and large-bank adoption, with government as one vertical. Denver HQ confirmed on the company's contact page; founding year is from general reference sources, not the site. Owned by Thoma Bravo."},
{"verdict":"scope_review","company_name":"CoreView","website":"https://www.coreview.com","description":"Microsoft 365 tenant governance, configuration management, and license optimization software for enterprise IT teams","hq_location":"Washington, DC","sector":"General Gov","category":"IT & AI Platforms","source_event":"NASCIO 2026","notes":"Horizontal Microsoft 365 management tool; named customers span higher ed, state government, banking, shipping, and nonprofits. Company lists a US HQ in Washington, DC, an EMEA HQ in Milan, Italy, and an Australian office. GovRAMP Premier Member. Founding year not found by these searches."},
{"verdict":"scope_review","company_name":"Cloudera","website":"https://www.cloudera.com","description":"Hybrid data lakehouse and enterprise AI platform sold to large organizations across all industries","hq_location":"Santa Clara, CA","year_founded":2008,"sector":"General Gov","category":"IT & AI Platforms","source_event":"NASCIO 2026","notes":"General enterprise data platform (Global 2000 positioning) with public sector as one vertical. HQ and founding year could not be confirmed on cloudera.com itself; both come from general reference sources and should be spot-checked."},
{"verdict":"scope_review","company_name":"Nomic Networks","website":"https://nomicnetworks.com","description":"Managed network detection and response and managed security operations for organizations with small IT teams","hq_location":"Dallas, TX","year_founded":1995,"sector":"General Gov","category":"IT & AI Platforms","source_event":"GMIS International 2026","notes":"Formerly Sentinel IPS. Delivered largely as a managed service rather than self-serve software, and sold across local government, banking, healthcare, and higher ed, so it is horizontal cybersecurity rather than a govtech product. HQ and founding year from Crunchbase/ZoomInfo-style profiles."},
{"verdict":"govtech","company_name":"For The Record","website":"https://fortherecord.com","description":"Digital courtroom audio and video recording, storage, and speech-to-text transcription software for courts","hq_location":"Denver, CO","year_founded":1993,"sector":"Courts & Justice","category":"Courts & Case Management","source_event":"NACM 2026","notes":"Also known as FTR. Tyler Technologies announced its acquisition of For The Record in February 2026 for about $212.5M and the company's own site confirms it has joined Tyler, so this may need to be merged into a Tyler record rather than tracked separately."},
{"verdict":"scope_review","company_name":"Zoom Communications","website":"https://www.zoom.com","description":"Video meetings, phone, chat, and contact center software sold to businesses, schools, and governments","hq_location":"San Jose, CA","year_founded":2011,"sector":"General Gov","category":"IT & AI Platforms","source_event":"CoSN 2026","notes":"Renamed from Zoom Video Communications to Zoom Communications, Inc. in 2024. Horizontal communications platform; education and government are two of many named verticals."},
{"verdict":"scope_review","company_name":"Logikcull","website":"https://www.logikcull.com","description":"Cloud e-discovery, legal hold, and public records request automation for law firms, corporations, government agencies, and schools","hq_location":"San Francisco, CA","year_founded":2004,"sector":"General Gov","category":"Courts & Justice","source_event":"CoSN 2026","notes":"Acquired by Reveal Data in August 2023 and now operates as a Reveal brand; the logikcull.com site is still live with its own product pages. Horizontal legal tech, with FOIA and public records handling as one workflow among corporate e-discovery use cases."},
{"verdict":"govtech","company_name":"Ativion","website":"https://www.ativion.com","description":"ContentKeeper web filtering and StudentKeeper student safety monitoring software for K-12 school districts","hq_location":"Nottingham, United Kingdom","year_founded":2002,"sector":"K-12 Schools","category":"School Safety","source_event":"CoSN 2026","notes":"Legal entity is Impero Solutions Ltd. trading as Ativion; ContentKeeper (founded 1998 in Canberra, Australia) was acquired by Impero in January 2022. Founding year 2002 refers to Impero and is reported as 2001 by some sources, so treat it as approximate. Backed by Investcorp."},
{"verdict":"govtech","company_name":"Droplet","website":"https://droplet.io","description":"No-code digital forms, approval workflow, and e-signature software for K-12 school districts","hq_location":"Lehi, UT","year_founded":2018,"sector":"K-12 Schools","category":"Operations & SIS","source_event":"CoSN 2026","notes":"HQ and founding year from PitchBook/Tracxn-style profiles and founder press; the company site does not state them. One source lists 2020 instead of 2018."}
]
json.dump(d,open(OUT,"w"),indent=1)
print(len(d["researched"]),"total")
