import json, os
OUT="/private/tmp/claude-501/-Users-wyethwest/bae54666-b02f-4b55-98ed-4e5a5f866107/scratchpad/dock-work/data/conference_intake/researched/batch-2.json"
r=[
{"verdict":"scope_review","company_name":"ASUENE USA Inc.","website":"https://asuene.com/us","description":"Carbon accounting and ESG disclosure software for enterprises, aimed mainly at manufacturers and their supply chains","hq_location":"Torrance, CA","sector":"General Gov","category":"Strategy & Performance","source_event":"NACUBO 2026","notes":"Given URL www.asuene.com does not resolve; canonical US site is asuene.com/us. US subsidiary of Asuene Inc. (Tokyo), relocated from Los Angeles to Torrance. Horizontal ESG platform sold across industry verticals (automotive, electronics, chemicals, consumer goods), not a public-sector product, despite exhibiting at NACUBO. Founding year not found by these searches."},
{"verdict":"govtech","company_name":"Ellucian","website":"https://www.ellucian.com","description":"Student information, finance, and HCM systems for colleges and universities","hq_location":"Reston, VA","year_founded":1968,"sector":"Higher Education","category":"IT & Administration","source_event":"NACUBO 2026","notes":"1968 is the founding of predecessor Datatel, cited by company profile databases and consistent with Ellucian's own '50+ years' claim; the Ellucian brand itself dates to the 2012 Datatel/SunGard Higher Education merger. Worth a second look if exact-brand founding year matters."},
{"verdict":"govtech","company_name":"Meadow","website":"https://www.meadowfi.com","description":"Student billing, payments, net price calculator, and pre-collections software for colleges and universities","hq_location":"New York, NY","sector":"Higher Education","category":"Business & Finance","source_event":"NACUBO 2026","notes":"Founding year not stated on the company site and not found by these searches."},
{"verdict":"govtech","company_name":"TouchNet, A Global Payments Company","website":"https://www.touchnet.com","description":"Campus commerce, tuition billing, and payment processing software for colleges and universities","hq_location":"Lenexa, KS","year_founded":1989,"sector":"Higher Education","category":"Business & Finance","source_event":"NACUBO 2026","notes":"touchnet.com returns Cloudflare 403 to both WebFetch and curl; details confirmed from TouchNet's own press/about listings and company directories. Owned by Global Payments."},
{"verdict":"govtech","company_name":"GivePulse","website":"https://www.givepulse.com","description":"Volunteer, service-learning, and community engagement management software for universities, school districts, cities, and nonprofits","hq_location":"Austin, TX","year_founded":2012,"sector":"Higher Education","category":"IT & Administration","source_event":"Animal Care Expo 2026","notes":"No URL was supplied; givepulse.com confirmed as the company's own site (about page states 2012 founding). Higher ed is its core market even though the source event was an animal welfare show."},
{"verdict":"govtech","company_name":"Allocore","website":"https://allocore.com","description":"Loan origination, grants management, and fraud prevention platform for federal agencies","hq_location":"Arlington, VA","sector":"General Gov","category":"Finance & ERP","source_event":"GFOA 2026","notes":"Federal-first (USDA, Dept. of Education, DFC) rather than state and local. FedRAMP High authorized. Founding year not found by these searches."},
{"verdict":"scope_review","company_name":"CoStar Real Estate Manager","website":"https://costarmanager.com","description":"Lease accounting and lease administration software for corporate, retail, and public-sector real estate portfolios","hq_location":"Atlanta, GA","sector":"General Gov","category":"Finance & ERP","source_event":"GFOA 2026","notes":"Horizontal lease accounting product sold across all industries; GASB 87 support is one compliance mode among ASC 842 and IFRS 16. Acquired Visual Lease, now merged into this brand. Part of CoStar Group. Founding year not found by these searches."},
{"verdict":"scope_review","company_name":"FinQuery","website":"https://finquery.com","description":"Lease, debt, and accrual accounting automation software for finance teams in any industry","hq_location":"Atlanta, GA","year_founded":2011,"sector":"General Gov","category":"Finance & ERP","source_event":"GFOA 2026","notes":"Formerly LeaseQuery. Horizontal accounting-compliance product; government issuers are one segment among corporates and CPA firms."},
{"verdict":"govtech","company_name":"MuniPro","website":"https://www.munipro.com","description":"Municipal bond market data, debt structuring, and issuer debt management software for government finance officers, underwriters, and municipal advisors","hq_location":"New York, NY","year_founded":2018,"sector":"General Gov","category":"Finance & ERP","source_event":"GFOA 2026","notes":"Judgment call: the flagship platform is an institutional muni desk sold to banks, advisors, and asset managers, while the government-facing product BondGov is free to issuers with paid workflow upgrades. Counted as govtech because the entire product is municipal-finance-specific, but the paying customer is often a financial intermediary."},
{"verdict":"scope_review","company_name":"Sage","website":"https://www.sage.com/en-us/","description":"Accounting, payroll, and ERP software for small and mid-sized businesses across all industries","hq_location":"Newcastle upon Tyne, United Kingdom","year_founded":1981,"sector":"General Gov","category":"Finance & ERP","source_event":"GFOA 2026","notes":"sage.com blocks automated fetch (Cloudflare 403) for both WebFetch and curl; details from company profile sources. Horizontal SMB accounting/ERP vendor with a public sector practice (Sage Intacct), not a govtech-specific product."}
]
os.makedirs(os.path.dirname(OUT),exist_ok=True)
json.dump({"researched":r},open(OUT,"w"),indent=1)
print(len(r),"written")
