import json
OUT="/private/tmp/claude-501/-Users-wyethwest/bae54666-b02f-4b55-98ed-4e5a5f866107/scratchpad/dock-work/data/conference_intake/researched/batch-2.json"
d=json.load(open(OUT))
d["researched"]+=[
{"verdict":"scope_review","company_name":"EfficientIP","website":"https://efficientip.com","description":"DNS, DHCP, and IP address management software with DNS security, sold to enterprises and service providers across all industries","hq_location":"West Chester, PA","year_founded":2004,"sector":"General Gov","category":"IT & AI Platforms","source_event":"EDUCAUSE 2026","notes":"Horizontal network infrastructure vendor; reference customers are Netflix, Heineken, Orange, Airbus, and Credit Agricole, with education one of six named verticals. Originally a French company (EfficientIP SAS); West Chester, PA is the address listed first on its contact page and appears to be the US HQ, so the corporate HQ in France is worth confirming. Founding year from the site's 'Since 2004'."},
{"verdict":"govtech","company_name":"FeedbackFruits","website":"https://feedbackfruits.com","description":"Peer review, group work, and AI feedback tools that plug into university learning management systems","hq_location":"Amsterdam, Netherlands","year_founded":2012,"sector":"Higher Education","category":"IT & Administration","source_event":"EDUCAUSE 2026","notes":"Second office in Boston, MA. Founding year from the company's own about page."},
{"verdict":"scope_review","company_name":"GoMeddo","website":"https://www.gomeddo.com","description":"Salesforce-native scheduling, booking, and resource reservation software sold across education, healthcare, hospitality, retail, and financial services","hq_location":"Laren, Netherlands","sector":"General Gov","category":"IT & AI Platforms","source_event":"EDUCAUSE 2026","notes":"Horizontal Salesforce ISV listing ten industries; education is one. Founding year not found by these searches."},
{"verdict":"scope_review","company_name":"HaloITSM","website":"https://usehalo.com/haloitsm","description":"IT service management, enterprise service management, and CRM software sold across public sector, retail, education, healthcare, and financial services","hq_location":"London, United Kingdom","sector":"General Gov","category":"IT & AI Platforms","source_event":"EDUCAUSE 2026","notes":"Corporate entity is Halo Service Solutions; HaloITSM is one product alongside HaloPSA, HaloCRM, and HaloCSM. Horizontal service-desk vendor across roughly fifteen named industries. Founding year not found by these searches."},
{"verdict":"govtech","company_name":"Intelligent Video Solutions","website":"https://ipivs.com","description":"VALT video observation and recording software for nursing simulation labs, clinical skills training, courtrooms, and child advocacy centers","hq_location":"Sussex, WI","sector":"Higher Education","category":"IT & Administration","source_event":"EDUCAUSE 2026","notes":"Known as IVS. Sells hardware and installation alongside the software, so part of the business is systems integration. Higher education is the lead market, with healthcare, government (law enforcement, courts, child advocacy), and corporate research as the others. Founding year not found by these searches."},
{"verdict":"govtech","company_name":"Lambent","website":"https://lambentspaces.com","description":"Wi-Fi-derived space utilization and occupancy analytics for university campuses and corporate real estate teams","year_founded":2017,"sector":"Higher Education","category":"IT & Administration","source_event":"EDUCAUSE 2026","notes":"Operates under parent Armored Things; 2017 comes from the about page's account of the company's origin. Corporate real estate is a co-equal market with higher ed, so it sits close to the scope-review line. HQ not published on the site and not found by these searches."},
{"verdict":"scope_review","company_name":"MyWorkDrive","website":"https://www.myworkdrive.com","description":"VPN-free secure remote access to on-premises and cloud file servers, sold across healthcare, education, government, legal, finance, and manufacturing","sector":"General Gov","category":"IT & AI Platforms","source_event":"EDUCAUSE 2026","notes":"Legal entity MyWorkDrive, LLC. Horizontal file-access product spanning seven named industries. HQ and founding year not published on the site and not found by these searches."},
{"verdict":"scope_review","company_name":"Orchestry","website":"https://www.orchestry.com","description":"Microsoft 365 workspace provisioning, lifecycle, and governance software for IT teams across construction, healthcare, higher education, legal, manufacturing, and public sector","sector":"General Gov","category":"IT & AI Platforms","source_event":"EDUCAUSE 2026","notes":"Legal entity Orchestry Software Inc. Horizontal Microsoft ecosystem ISV; overlaps directly with the CoreView candidate from NASCIO 2026. HQ and founding year not published on the site and not found by these searches."},
{"verdict":"govtech","company_name":"Pope Tech","website":"https://pope.tech","description":"Automated and guided web accessibility testing for university websites and Canvas course content","hq_location":"Providence, UT","sector":"Higher Education","category":"IT & Administration","source_event":"EDUCAUSE 2026","notes":"Built on the WAVE engine from WebAIM at Utah State University. Higher education is the core market, though the site also cites companies and nonprofits as customers. Legal name is Pope Tech Corporation per the candidate list; the site uses Pope Tech. Founding year not found by these searches."},
{"verdict":"scope_review","company_name":"Red Hat","website":"https://www.redhat.com","description":"Enterprise Linux, Kubernetes, automation, and AI platform subscriptions sold to large organizations in every industry","hq_location":"Raleigh, NC","year_founded":1993,"sector":"General Gov","category":"IT & AI Platforms","source_event":"EDUCAUSE 2026","notes":"An IBM subsidiary since 2019. Horizontal enterprise open source vendor with an academic program; not govtech-specific."}
]
json.dump(d,open(OUT,"w"),indent=1)
print(len(d["researched"]),"total")
