import json
OUT="/private/tmp/claude-501/-Users-wyethwest/bae54666-b02f-4b55-98ed-4e5a5f866107/scratchpad/dock-work/data/conference_intake/researched/batch-2.json"
d=json.load(open(OUT))
d["researched"]+=[
{"verdict":"govtech","company_name":"Intellischool","website":"https://intellischool.co","description":"Data warehouse and analytics platform that unifies SIS, LMS, assessment, and attendance data for K-12 schools and districts","hq_location":"Melbourne, Australia","sector":"K-12 Schools","category":"Operations & SIS","source_event":"CoSN 2026","notes":"Legal entity Intellischool Holdings Pty Ltd, with operations in Australia/New Zealand, Canada, and the US. Founding year not stated on the site and not found by these searches; the 2026 on the page is a copyright notice, not a founding date."},
{"verdict":"govtech","company_name":"Resimplifi","website":"https://resimplifi.com","description":"Automatically maintained commercial sites and buildings listing database for economic development organizations","sector":"Housing & Community Dev","category":"Planning & Economic Development","source_event":"IEDC 2026","notes":"Customers named on the site are public and quasi-public EDOs, chambers, and city and county development authorities. HQ and founding year are not published anywhere on the site and were not found by these searches."},
{"verdict":"scope_review","company_name":"ScreenSteps","website":"https://www.screensteps.com","description":"Knowledge base, SOP authoring, and in-app agent guidance software for contact centers and regulated back offices","hq_location":"McLean, VA","sector":"General Gov","category":"IT & AI Platforms","source_event":"APHSA 2026","notes":"Horizontal knowledge-operations tool; the industries it names are credit unions, banks, farm credit associations, contact centers, and law firms, with human services agencies as an adjacent buyer. Founding year not found by these searches."},
{"verdict":"govtech","company_name":"Cúram by Merative","website":"https://www.merative.com/social-program-management","description":"Social program management platform for eligibility, enrollment, child welfare, and case management at health and human services agencies","hq_location":"Ann Arbor, MI","sector":"Health & Human Services","category":"Benefits & Medicaid Systems","source_event":"APHSA 2026","notes":"No URL was supplied. Cúram is a product line, not a standalone company: originally Curam Software, acquired by IBM in 2011 and carried into Merative when Francisco Partners bought IBM Watson Health in 2022. Deployed by Minnesota, New York City, Canada, and Scotland. Merative's founding year is best recorded as the 2022 carve-out but is not stated on the page, so it is omitted."},
{"verdict":"govtech","company_name":"HousingOS","website":"https://gohousingos.com","description":"Program administration software for municipal CDBG, HOME, and housing rehabilitation funds covering intake, construction management, and monitoring","sector":"Housing & Community Dev","category":"Housing & Assistance","source_event":"NAHRO 2026","notes":"Candidate name 'Housing Programs Software' is the company; HousingOS is the flagship product and the name used across the site, with ApplicationOS as a companion. The site's copyright reads 2000-2026, which hints at a long history but is not a stated founding year. HQ not published on the site and not found by these searches."},
{"verdict":"scope_review","company_name":"PaymentVision","website":"https://www.paymentvision.com","description":"Payment gateway for card, ACH, and check payments taken by phone, web, and API, sold to lenders, collectors, healthcare billers, utilities, and government agencies","hq_location":"Jacksonville, FL","year_founded":1988,"sector":"General Gov","category":"Procurement & Payments","source_event":"NAHRO 2026","notes":"A brand of Autoscribe Corporation. Horizontal biller-facing payments processor; housing authorities and municipalities are one of five named verticals alongside collections and consumer finance."},
{"verdict":"scope_review","company_name":"Amigo AI","website":"https://amigo.ai","description":"Platform for building and deploying AI clinical agents that automate patient-facing workflows for healthcare providers","sector":"Health & Human Services","category":"Behavioral Health","source_event":"NatCon 2026","notes":"Judgment call worth a second look: the buyers are clinics and health systems across primary care, orthopedics, women's health, oncology, and behavioral health, so it is a healthcare AI vendor rather than a public-agency product, despite exhibiting at NatCon. HQ and founding year are not published on the site and were not found by these searches."},
{"verdict":"govtech","company_name":"CHESS Health","website":"https://www.chess.health","description":"Digital substance use disorder prevention, intervention, and recovery support platform for treatment providers, state and county health agencies, drug courts, and Medicaid plans","hq_location":"Rochester, NY","sector":"Health & Human Services","category":"Behavioral Health","source_event":"NatCon 2026","notes":"Commercialized from the University of Wisconsin's A-CHESS research; the site's history page cites a 2014 JAMA Psychiatry study, a 2016 chairman appointment, and a 2017 CEO hire, but never states a founding year, so none is recorded."},
{"verdict":"govtech","company_name":"CredibleMind","website":"https://crediblemind.com","description":"Behavioral health and wellbeing content, screening, and care-navigation platform deployed by public health departments, health plans, and health systems for their communities","hq_location":"Sausalito, CA","sector":"Health & Human Services","category":"Behavioral Health","source_event":"NatCon 2026","notes":"Legal name CredibleMind, Inc. Partners include NACCHO and the American Hospital Association, and public health is a named buyer segment, but employers and commercial health plans are also core customers, so the public-sector share is worth checking. Founding year not found by these searches."},
{"verdict":"govtech","company_name":"EnSoftek, Inc. (DrCloudEHR)","website":"https://www.drcloudehr.com","description":"Behavioral health electronic health record and revenue cycle software for mental health, substance use, IDD, and CCBHC providers and public health agencies","hq_location":"Beaverton, OR","sector":"Health & Human Services","category":"Behavioral Health","source_event":"NatCon 2026","notes":"EnSoftek, Inc. is the legal entity; DrCloudEHR is the product. Second office in Hinsdale, IL. FedRAMP and FISMA High authorized. Founding year not found by these searches."}
]
json.dump(d,open(OUT,"w"),indent=1)
print(len(d["researched"]),"total")
