#!/usr/bin/env python3
"""Register the state and local chapter conferences as a mining worklist.

    python3 scripts/register_state_events.py --csv ~/Downloads/sources_state.csv
    python3 scripts/register_state_events.py --csv ... --write

WHY THESE MATTER. The board's 126 conferences are national: ICMA, PWX, IACP,
NRPA. National floors are where the big vendors stand, and the board already
has the big vendors. The companies it is MISSING are regional - a records
system sold in four states, a parks scheduler with sixty customers - and those
companies cannot afford a national booth. They stand at the state chapter.
359 of those events, against 126 national ones, is the largest single source
of new companies available to this project.

WHY THEY ARE NOT CONFERENCES YET, AND WHY THIS IS A SEPARATE FILE.

  NO EXHIBITOR LIST. Every row arrives with an empty directory_url. The chain
  that turns a conference into companies is exhibitor_url -> fetch the list ->
  conference_intake matches names -> a company gets the event in its
  description and `source: "conference sweep: <tag>"`. With no directory there
  is nothing to mine and nothing to put on a company page. This is already the
  binding constraint: of the 126 conferences on file, 45 have an exhibitor_url
  and 12 have been swept.

  A THIRD OF THE NAMES ARE GUESSES. 130 of 359 carry name_confidence
  "pattern", meaning the organisation's name was generated by filling a state
  into a template - "APWA {state} Chapter", "{state} Emergency Management
  Association". The generator says so itself: "PATTERN entries are scaffolding
  you resolve during the URL-finding pass." Some of those organisations exist
  under exactly that name. Some do not.

  conferences.json is PUBLIC - build_site renders a page per event - so a
  generated name written there is an invented organisation published on a
  live site. CLAUDE.md's rule is the whole reason this file exists separately:
  never invent a fact to fill a field.

  est_exhibitors is likewise an ESTIMATE, not a count. It is carried through
  as `est_exhibitors` and never as `exhibitors`, so no total computed from
  this file can pass itself off as a measurement.

WHAT PROMOTES A ROW OUT OF HERE. Two things, both evidence: a real
exhibitor or sponsor directory URL that answers, and - for a pattern row - a
confirmation that the organisation exists under that name. Until both, a row
sits here as work to do rather than a fact on a page.
"""
from __future__ import annotations

import argparse
import csv
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = DATA / "state_events.json"

FIELDS = ("org_code", "org_name", "event_name", "vertical", "department", "geo",
          "name_confidence", "est_exhibitors", "source_type", "parent_national")


def norm(s: str) -> str:
    return re.sub(r"[^a-z0-9]", "", (s or "").lower())


def existing_tags() -> set:
    """Everything conferences.json already knows, by name and by tag.

    A state event that duplicates a national one already on file must not be
    registered twice - the sweep would then attribute one exhibitor list to
    two events and double-count every company on it.
    """
    # NOT swallowed. An unreadable conferences.json returning an empty set
    # would switch this guard off silently and register every national event
    # a second time - the exact double-count it exists to prevent.
    try:
        conf = json.loads((DATA / "conferences.json").read_text())["conferences"]
    except Exception as exc:                            # noqa: BLE001
        raise SystemExit(f"cannot read conferences.json ({type(exc).__name__}: "
                         f"{exc}) - refusing to register without it, because "
                         f"the duplicate guard would be off") from exc
    out = set()
    for c in conf:
        for k in ("conference", "event_tag"):
            if c.get(k):
                out.add(norm(c[k]))
        for t in (c.get("prior_tags") or []):
            out.add(norm(t))
    return out


def read_csv(path: pathlib.Path) -> list[dict]:
    rows = list(csv.DictReader(path.open()))
    missing = [f for f in FIELDS if rows and f not in rows[0]]
    if missing:
        raise SystemExit(f"the csv is missing columns: {', '.join(missing)}")
    return rows


def register(rows: list[dict], known: set) -> tuple[list, list]:
    """Shape each row for the catalogue, holding back anything already known."""
    out, skipped = [], []
    seen = set()
    for r in rows:
        code = (r.get("org_code") or "").strip()
        event = (r.get("event_name") or "").strip()
        if not code or not event:
            continue
        if norm(event) in known:
            skipped.append((code, event, "already in conferences.json"))
            continue
        if code in seen:
            skipped.append((code, event, "duplicate org_code in the csv"))
            continue
        seen.add(code)
        try:
            est = int(r.get("est_exhibitors") or 0)
        except ValueError:
            est = 0
        out.append({
            "org_code": code,
            "org_name": (r.get("org_name") or "").strip(),
            "event_name": event,
            "vertical": (r.get("vertical") or "").strip(),
            "department": (r.get("department") or "").strip(),
            "geo": (r.get("geo") or "").strip(),
            # CARRIED, NEVER DROPPED. This is the field that decides whether a
            # row may ever be promoted without a person looking at it.
            "name_confidence": (r.get("name_confidence") or "").strip(),
            # AN ESTIMATE. Named est_ so a sum of it can never be reported as
            # a count of anybody's exhibitors.
            "est_exhibitors": est,
            "parent_national": (r.get("parent_national") or "").strip(),
            # What this row still needs. Both are the URL-finding pass's job.
            "directory_url": None,
            "org_url": None,
            "status": "needs_url",
            "promoted": False,
        })
    return out, skipped


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", required=True)
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args()

    rows = read_csv(pathlib.Path(a.csv).expanduser())
    known = existing_tags()
    events, skipped = register(rows, known)

    by_conf: dict[str, int] = {}
    by_vert: dict[str, int] = {}
    for e in events:
        by_conf[e["name_confidence"]] = by_conf.get(e["name_confidence"], 0) + 1
        by_vert[e["vertical"]] = by_vert.get(e["vertical"], 0) + 1

    print(f"{len(rows)} row(s) in the csv, {len(events)} to register, "
          f"{len(skipped)} held back")
    for code, event, why in skipped[:10]:
        print(f"  skip  {code:16} {event[:38]:40} {why}")
    print()
    print("  by name confidence: " + "  ".join(
        f"{k}={v}" for k, v in sorted(by_conf.items())))
    print("  by vertical:        " + "  ".join(
        f"{k}={v}" for k, v in sorted(by_vert.items(), key=lambda kv: -kv[1])))
    print()
    named = by_conf.get("named", 0)
    print(f"  {named} carry a real organisation name and need only a directory url")
    print(f"  {by_conf.get('pattern', 0)} carry a GENERATED name and need the "
          f"organisation confirmed to exist before anything else")
    print(f"\n  none of them can produce a company until a directory url is "
          f"found - that is the next pass, and it is what this file is for")

    if not a.write:
        print("\n  LOOKED ONLY. Re-run with --write to register them.")
        return 0

    payload = {
        "note": ("State and local chapter conferences, staged for the "
                 "URL-finding pass. NOT conferences.json: nothing here has a "
                 "verified exhibitor directory, and name_confidence 'pattern' "
                 "means the organisation's name was generated from a template "
                 "rather than observed. A row is promoted only once it has a "
                 "directory that answers and - if generated - a confirmation "
                 "that the organisation exists under that name. "
                 "est_exhibitors is an estimate and is never a count."),
        "events": events,
    }
    tmp = OUT.with_suffix(".tmp")
    tmp.write_text(json.dumps(payload, indent=1) + "\n")
    try:
        json.loads(tmp.read_text())
    except json.JSONDecodeError:
        tmp.unlink(missing_ok=True)
        print("refused: the result did not parse", file=sys.stderr)
        return 1
    tmp.replace(OUT)
    print(f"\n  wrote {len(events)} event(s) to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
